FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app

COPY . .

RUN mvn -pl common,stockdata_producer_service -am clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/stockdata_producer_service/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]